<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<button type="button" class="btn btn-default btn-circle" data-toggle="modal" data-target="#myModal">
    open calculator
</button>


<div class="modal fade modal-draggable" id="myModal" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CALCOLATRICE</h4>
            </div>
            <div class="modal-body">
                <div class="calcolatrice"></div>
            </div>
        </div>
    </div>
</div>




<?php echo $this->headScript()
    ->prependFile($this->basePath('js/calcolatrice.js')); ?>