<button type="button" class="btn btn-default btn-circle" data-toggle="modal" data-target="#myModal">

    open calculator
</button>

<div class="modal fade" id="myModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">CALCOLATRICE</h4>
            </div>
            <div class="modal-body">
                <div class="calcolatrice"></div>
            </div>
        </div>
    </div>
</div>




<?php echo $this->headScript()
    ->prependFile($this->basePath('js/calcolatrice.js')); ?>